(when (version<= emacs-version "24.2")
    (require 'cl-lib))
(require 'yasnippet "../yasnippet")
(yas-global-mode 1)
(define-key yas-minor-mode-map [(tab)] nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
(setq yas-trigger-key nil)
(define-key yas-minor-mode-map (kbd "C-c SPC") 'yas-expand)
(define-key yas-minor-mode-map (kbd "C-c s") 'yas-insert-snippet)
(setq yas-prompt-functions '(yas-completing-prompt yas-no-prompt))
